[package]
name = "stones"
version = "0.1.0"
authors = ["Spencer Gabhart <sgabhart2230@gmail.com>"]

[dependencies]
piston = "0.32.0"
piston_window = "0.65.0"
piston2d-opengl_graphics = "0.43.0"
piston2d-graphics = "0.21.1"
find_folder = "0.3.0"
